# GPU
ARG CUDA_VER=11.8.0
ARG CUDA_PATH=11.8
ARG CUDNN_VER=8

# OS
ARG UBUNTU_VER=20.04

# Python
ARG PYTHON_VER=38

# 베이스 이미지 설정
FROM nvidia/cuda:${CUDA_VER}-cudnn${CUDNN_VER}-devel-ubuntu${UBUNTU_VER}

#Set the TORCH_CUDA_ARCH_LIST
ENV TORCH_CUDA_ARCH_LIST=${TORCH_CUDA_ARCH_LIST}

# Set the PYTHONPATH and LD_LIBRARY_PATH environment variable to include the CUDA libraries
ENV PYTHONPATH=/usr/local/cuda-${CUDA_PATH}/lib64
ENV LD_LIBRARY_PATH=/usr/local/cuda-${CUDA_PATH}/lib64

# Set the CUDA_PATH and CUDA_HOME environment variable to point to the CUDA installation directory
ENV CUDA_PATH=/usr/local/cuda-${CUDA_PATH}
ENV CUDA_HOME=/usr/local/cuda-${CUDA_PATH}

# 필요한 파일 copy 하기
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt

RUN apt update && \
    apt install -y pip

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements.txt