# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12models/model.proto\"\x1f\n\x10InferenceRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"#\n\x11InferenceResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2?\n\tInference\x12\x32\n\tgetResult\x12\x11.InferenceRequest\x1a\x12.InferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INFERENCEREQUEST']._serialized_start=22
  _globals['_INFERENCEREQUEST']._serialized_end=53
  _globals['_INFERENCERESPONSE']._serialized_start=55
  _globals['_INFERENCERESPONSE']._serialized_end=90
  _globals['_INFERENCE']._serialized_start=92
  _globals['_INFERENCE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
